import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "@/providers/session-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { QueryProvider } from "@/providers/query-provider";
import { StoreProvider } from "@/providers/store-provider";
import { ConfirmProvider } from "@/providers/confirm-provider";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <QueryProvider>
              <StoreProvider>
                <ConfirmProvider>
                  {children}
                  <Toaster 
                    position="bottom-right" 
                  theme="system" 
                  toastOptions={{
                    classNames: {
                      toast: "rounded-2xl border-none shadow-2xl backdrop-blur-xl bg-white/95 dark:bg-slate-900/95 p-4 flex items-center font-sans",
                      title: "text-sm font-bold text-slate-800 dark:text-white",
                      description: "text-sm text-slate-500 dark:text-slate-400 font-medium",
                      error: "bg-rose-50 dark:bg-rose-500/10 border border-rose-100 dark:border-rose-500/20 text-rose-600 dark:text-rose-400",
                      success: "bg-teal-50 dark:bg-brand-teal/10 border border-teal-100 dark:border-brand-teal/20 text-brand-teal",
                      warning: "bg-amber-50 dark:bg-amber-500/10 border border-amber-100 dark:border-amber-500/20 text-amber-600 dark:text-amber-400",
                      info: "bg-blue-50 dark:bg-blue-500/10 border border-blue-100 dark:border-blue-500/20 text-blue-600 dark:text-blue-400"
                    }
                  }} 
                />
                </ConfirmProvider>
              </StoreProvider>
            </QueryProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
